CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	status TEXT DEFAULT 启用 NOT NULL
, "type" TEXT NOT NULL)


CREATE TABLE excels (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	date TEXT NOT NULL
, "path" TEXT NOT NULL)


CREATE TABLE missions (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	excel_id INTEGER NOT NULL,
	code TEXT NOT NULL,
	name TEXT NOT NULL,
	assigned TEXT NOT NULL DEFAULT ''
)